"""
accommodation.py — Accommodation Engine (Physics-First)
========================================================

Unifies tectonic subsidence + eustasy + sediment loading + compaction
into a single simulation that produces accommodation space through time.

This is the DRIVER of stratigraphy. Not cartoon sea-level curves.

Physics:
  - Tectonic subsidence: McKenzie (1978) exponential thermal decay
  - Eustasy: user-supplied curve or constant rate
  - Sediment loading: Airy isostasy (Steckler & Watts 1978)
  - Compaction: Athy (1930) porosity-depth law
  - Accommodation = water_depth + sediment_thickness (Jervey 1988)

Replaces: the "accommodation" concept that LST/TST/HST tries to name
but never actually computes.

DITEMPA BUKAN DIBERI — Forged, Not Given.
Forged: 2026-07-03 — the extinction event.
"""

from __future__ import annotations

import math
from enum import StrEnum

from pydantic import BaseModel, Field

# ═══════════════════════════════════════════════════════════════════════════
# Constants
# ═══════════════════════════════════════════════════════════════════════════

RHO_MANTLE_KGM3: float = 3300.0
RHO_WATER_KGM3: float = 1000.0
RHO_SEDIMENT_KGM3: float = 2400.0

# Athy porosity-depth constants (Sclater & Christie 1980)
PHI0_SAND: float = 0.49
C_SAND_PER_KM: float = 0.27
PHI0_SHALE: float = 0.63
C_SHALE_PER_KM: float = 0.51


# ═══════════════════════════════════════════════════════════════════════════
# Enums
# ═══════════════════════════════════════════════════════════════════════════


class SurfaceType(StrEnum):
    """Types of surfaces generated by the accommodation engine."""

    EROSION = "erosion"  # exposure, subaerial erosion
    FLOODING = "flooding"  # marine flooding surface
    MAXIMUM_FLOODING = "maximum_flooding"  # MFS — peak water depth
    RAVINEMENT = "ravinement"  # wave ravinement surface
    SEQUENCE_BOUNDARY = "sequence_boundary"  # subaerial unconformity
    CONFORMABLE = "conformable"  # continuous deposition


class StackingPattern(StrEnum):
    """Stacking patterns EMERGE from physics, not from rules."""

    PROGRADATIONAL = "progradational"  # shallowing upward
    RETROGRADATIONAL = "retrogradational"  # deepening upward
    AGGRADATIONAL = "aggradational"  # constant depth
    DEGRADATIONAL = "degradational"  # erosion-dominated


# ═══════════════════════════════════════════════════════════════════════════
# Input/Output Schemas
# ═══════════════════════════════════════════════════════════════════════════


class EustaticPoint(BaseModel):
    """A single point on the eustatic sea-level curve."""

    time_ma: float = Field(..., ge=0.0, description="Time (Ma), 0 = present")
    sea_level_m: float = Field(..., description="Sea level relative to present (m)")


class AccommodationRequest(BaseModel):
    """Input for the accommodation engine.

    All rates are positive = subsidence/rise, negative = uplift/fall.
    """

    # Tectonic subsidence (from McKenzie rift kinematics)
    initial_subsidence_km: float = Field(
        ...,
        ge=0.0,
        le=15.0,
        description="Sᵢ — initial fault-controlled subsidence (km)",
    )
    thermal_subsidence_rate_mm_yr: float = Field(
        default=0.05,
        ge=0.0,
        le=5.0,
        description="Thermal subsidence rate (mm/yr). Post-rift: ~0.02-0.1",
    )
    tau_ma: float = Field(
        default=62.0,
        ge=1.0,
        le=200.0,
        description="Thermal decay constant (Myr). McKenzie default: 62 Ma",
    )

    # Eustasy
    eustatic_curve: list[EustaticPoint] | None = Field(
        default=None,
        description="Sea-level curve through time. If None, uses constant_rate.",
    )
    eustatic_rate_mm_yr: float = Field(
        default=0.0,
        ge=-5.0,
        le=5.0,
        description="Constant eustatic rate (mm/yr). Ignored if curve provided.",
    )

    # Sediment supply
    sediment_supply_rate_m_myr: float = Field(
        default=50.0,
        ge=0.0,
        le=5000.0,
        description="Sediment accumulation rate (m/Myr) at the reference point",
    )
    sediment_supply_variation: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Random variation in supply rate (0=constant, 1=±100%)",
    )

    # Basin geometry
    initial_water_depth_m: float = Field(
        default=50.0,
        ge=0.0,
        le=5000.0,
        description="Initial water depth at the reference point (m)",
    )
    basin_width_km: float = Field(
        default=50.0,
        ge=1.0,
        le=1000.0,
        description="Basin width for flexural correction (km)",
    )

    # Simulation
    duration_ma: float = Field(
        ...,
        gt=0.0,
        le=300.0,
        description="Simulation duration (Myr)",
    )
    time_step_myr: float = Field(
        default=0.5,
        gt=0.0,
        le=10.0,
        description="Time step (Myr)",
    )

    # Lithology (for compaction)
    dominant_lithology: str = Field(
        default="sandstone",
        description="Dominant lithology (sandstone, shale, limestone)",
    )


class AccommodationStep(BaseModel):
    """State at a single time step."""

    time_ma: float = Field(..., description="Time (Ma)")
    tectonic_subsidence_m: float = Field(..., description="Cumulative tectonic subsidence (m)")
    eustatic_sea_level_m: float = Field(..., description="Sea level at this time (m)")
    sediment_thickness_m: float = Field(..., description="Sediment thickness at this step (m)")
    sediment_load_subsidence_m: float = Field(..., description="Isostatic subsidence from sediment load (m)")
    total_accommodation_m: float = Field(..., description="Total accommodation space (m)")
    water_depth_m: float = Field(..., description="Water depth (m)")
    surface_type: SurfaceType = Field(..., description="Surface generated at this step")
    stacking_pattern: StackingPattern = Field(..., description="Stacking pattern at this step")
    is_flooding_surface: bool = Field(default=False)
    is_maximum_flooding: bool = Field(default=False)
    is_sequence_boundary: bool = Field(default=False)
    erosion_m: float = Field(default=0.0, description="Erosion at this step (m)")


class AccommodationResult(BaseModel):
    """Full accommodation simulation result."""

    steps: list[AccommodationStep] = Field(..., description="Time steps")
    total_subsidence_m: float = Field(..., description="Total tectonic subsidence (m)")
    total_eustatic_change_m: float = Field(..., description="Net eustatic change (m)")
    total_sediment_m: float = Field(..., description="Total sediment deposited (m)")
    num_flooding_surfaces: int = Field(default=0)
    num_erosion_surfaces: int = Field(default=0)
    num_sequence_boundaries: int = Field(default=0)
    num_maximum_flooding: int = Field(default=0)
    emergent_stacking: list[StackingPattern] = Field(
        default_factory=list,
        description="Stacking patterns that emerged from physics",
    )
    confidence: float = Field(default=0.75, ge=0.0, le=0.90)
    epistemic_label: str = Field(default="DER")
    assumptions: list[str] = Field(default_factory=list)
    evidence_gaps: list[str] = Field(default_factory=list)
    note: str = Field(default="")


# ═══════════════════════════════════════════════════════════════════════════
# Physics Kernels — Pure Functions
# ═══════════════════════════════════════════════════════════════════════════


def tectonic_subsidence_at_time(
    si_km: float,
    thermal_rate_mm_yr: float,
    tau_ma: float,
    time_ma: float,
) -> float:
    """Tectonic subsidence at time t (m).

    S(t) = Sᵢ + ∫₀ᵗ thermal_rate · exp(-t'/τ) dt'
    S(t) = Sᵢ + thermal_rate · τ · (1 - exp(-t/τ))

    where thermal_rate is in mm/yr and τ is in Myr.
    Unit conversion: 1 mm/yr × 1 Myr = 1000 m.
    """
    si_m = si_km * 1000.0
    # Thermal contribution: integral of exponential decay
    thermal_m = thermal_rate_mm_yr * tau_ma * (1.0 - math.exp(-time_ma / tau_ma))
    return si_m + thermal_m


def sediment_load_isostasy(
    sediment_thickness_m: float,
    rho_sed: float = RHO_SEDIMENT_KGM3,
    rho_water: float = RHO_WATER_KGM3,
    rho_mantle: float = RHO_MANTLE_KGM3,
) -> float:
    """Isostatic subsidence from sediment loading (Airy isostasy).

    ΔS = T_sed × (ρs - ρw) / (ρm - ρw)

    Steckler & Watts (1978), Allen & Allen (2005, eq. 9.17).
    Returns subsidence in meters.
    """
    ratio = (rho_sed - rho_water) / (rho_mantle - rho_water)
    return sediment_thickness_m * ratio


def decompact_thickness(
    present_thickness_m: float,
    depth_km: float,
    phi0: float = PHI0_SAND,
    c_per_km: float = C_SAND_PER_KM,
) -> float:
    """Restore compacted thickness to original depositional thickness.

    Uses Athy (1930) porosity-depth law: φ(z) = φ₀ · exp(-c·z)

    Solid grain thickness is conserved:
      T_solid = T_present × (1 - φ_avg_present)
      T_original = T_solid / (1 - φ₀)
    """
    # Average porosity over the depth interval
    z_top = max(0.0, depth_km - present_thickness_m / 1000.0)
    z_bot = depth_km
    if z_bot <= z_top:
        phi_avg = phi0
    else:
        # Analytical average of exponential over interval
        integral = phi0 / c_per_km * (math.exp(-c_per_km * z_top) - math.exp(-c_per_km * z_bot))
        phi_avg = integral / (z_bot - z_top) if (z_bot - z_top) > 0 else phi0

    solid_fraction = 1.0 - phi_avg
    surface_porosity_fraction = 1.0 - phi0
    if surface_porosity_fraction <= 0:
        return present_thickness_m
    return present_thickness_m * solid_fraction / surface_porosity_fraction


def get_eustatic_level(
    time_ma: float,
    eustatic_curve: list[EustaticPoint] | None = None,
    constant_rate_mm_yr: float = 0.0,
) -> float:
    """Get eustatic sea level at a given time (m).

    If curve provided, linearly interpolates. Otherwise uses constant rate.
    """
    if eustatic_curve and len(eustatic_curve) >= 2:
        # Sort by time (descending = oldest first)
        sorted_pts = sorted(eustatic_curve, key=lambda p: p.time_ma, reverse=True)
        # Find bracketing points
        for i in range(len(sorted_pts) - 1):
            t1, sl1 = sorted_pts[i].time_ma, sorted_pts[i].sea_level_m
            t2, sl2 = sorted_pts[i + 1].time_ma, sorted_pts[i + 1].sea_level_m
            if t1 >= time_ma >= t2:
                # Linear interpolation
                if abs(t1 - t2) < 1e-10:
                    return sl1
                frac = (t1 - time_ma) / (t1 - t2)
                return sl1 + frac * (sl2 - sl1)
        # Extrapolation: use nearest point
        if time_ma > sorted_pts[0].time_ma:
            return sorted_pts[0].sea_level_m
        return sorted_pts[-1].sea_level_m
    else:
        # Constant rate: sea level change = rate × time
        return constant_rate_mm_yr * time_ma


# ═══════════════════════════════════════════════════════════════════════════
# Main Simulation
# ═══════════════════════════════════════════════════════════════════════════


def simulate_accommodation(req: AccommodationRequest) -> AccommodationResult:
    """Run the accommodation simulation.

    At each time step:
    1. Compute tectonic subsidence (McKenzie exponential)
    2. Get eustatic sea level (from curve or constant rate)
    3. Compute accommodation = water_depth + possible sediment
    4. Distribute sediment into accommodation
    5. Compute sediment loading isostasy
    6. Classify surface type and stacking pattern from PHYSICS

    Surfaces and patterns EMERGE — they are not assigned by rules.

    F2 TRUTH: all outputs are DER (derived from physics models).
    F7 HUMILITY: confidence capped at 0.90.
    """
    n_steps = max(2, int(req.duration_ma / req.time_step_myr) + 1)
    dt = req.duration_ma / (n_steps - 1)

    # Lithology params for compaction
    if req.dominant_lithology.lower() in ("shale", "mudstone", "clay"):
        _phi0, _c_per_km = PHI0_SHALE, C_SHALE_PER_KM
    else:
        _phi0, _c_per_km = PHI0_SAND, C_SAND_PER_KM

    steps: list[AccommodationStep] = []
    prev_water_depth = req.initial_water_depth_m
    prev_stacking = StackingPattern.AGGRADATIONAL
    cumulative_sediment = 0.0
    cumulative_subsidence_m = 0.0
    prev_eustatic = get_eustatic_level(
        req.duration_ma,
        req.eustatic_curve,
        req.eustatic_rate_mm_yr,
    )

    # Tracking for MFS detection
    max_water_depth = req.initial_water_depth_m

    for i in range(n_steps):
        t = req.duration_ma - i * dt  # time goes from oldest to youngest

        # 1. Tectonic subsidence at this time
        tect_sub_m = tectonic_subsidence_at_time(
            req.initial_subsidence_km,
            req.thermal_subsidence_rate_mm_yr,
            req.tau_ma,
            t,
        )

        # 2. Eustatic sea level
        eustatic_m = get_eustatic_level(t, req.eustatic_curve, req.eustatic_rate_mm_yr)
        eustatic_m - prev_eustatic

        # 3. Sediment loading isostasy
        sed_load_m = sediment_load_isostasy(cumulative_sediment)

        # 4. Total accommodation
        # Accommodation = space available for sediment above basement
        total_accommodation = tect_sub_m + eustatic_m + sed_load_m

        # 5. Water depth = accommodation - sediment fill
        water_depth = total_accommodation - cumulative_sediment
        water_depth = max(0.0, water_depth)

        # 6. Sediment deposition for this step
        # Sediment fills available accommodation, bounded by supply rate
        available_accommodation = water_depth
        sediment_this_step = min(
            req.sediment_supply_rate_m_myr * dt,
            available_accommodation,
        )
        sediment_this_step = max(0.0, sediment_this_step)

        # 7. Erosion if accommodation is negative (sea-level fall + uplift)
        erosion_this_step = 0.0
        if total_accommodation < cumulative_sediment:
            erosion_this_step = cumulative_sediment - total_accommodation
            cumulative_sediment = total_accommodation

        cumulative_sediment += sediment_this_step
        cumulative_subsidence_m = tect_sub_m

        # 8. Classify surface from PHYSICS
        surface_type = SurfaceType.CONFORMABLE
        is_fs = False
        is_mfs = False
        is_sb = False

        # Erosion surface: accommodation dropped below sediment
        if erosion_this_step > 0.1:
            surface_type = SurfaceType.EROSION
            if erosion_this_step > 1.0:
                surface_type = SurfaceType.SEQUENCE_BOUNDARY
                is_sb = True

        # Flooding surface: water depth increased significantly
        elif water_depth > prev_water_depth + 2.0:
            surface_type = SurfaceType.FLOODING
            is_fs = True

        # Maximum flooding: deepest water
        if water_depth > max_water_depth + 1.0:
            max_water_depth = water_depth
            is_mfs = True
            surface_type = SurfaceType.MAXIMUM_FLOODING

        # Ravinement: flooding + erosion of underlying sediment
        if is_fs and erosion_this_step > 0.05:
            surface_type = SurfaceType.RAVINEMENT

        # 9. Stacking pattern from PHYSICS (not rules)
        stacking = prev_stacking
        if water_depth > prev_water_depth + 1.0:
            stacking = StackingPattern.RETROGRADATIONAL
        elif water_depth < prev_water_depth - 1.0:
            stacking = StackingPattern.PROGRADATIONAL
        elif abs(water_depth - prev_water_depth) <= 1.0:
            stacking = StackingPattern.AGGRADATIONAL
        if erosion_this_step > 1.0:
            stacking = StackingPattern.DEGRADATIONAL

        steps.append(
            AccommodationStep(
                time_ma=round(t, 3),
                tectonic_subsidence_m=round(tect_sub_m, 1),
                eustatic_sea_level_m=round(eustatic_m, 1),
                sediment_thickness_m=round(cumulative_sediment, 1),
                sediment_load_subsidence_m=round(sed_load_m, 1),
                total_accommodation_m=round(total_accommodation, 1),
                water_depth_m=round(water_depth, 1),
                surface_type=surface_type,
                stacking_pattern=stacking,
                is_flooding_surface=is_fs,
                is_maximum_flooding=is_mfs,
                is_sequence_boundary=is_sb,
                erosion_m=round(erosion_this_step, 2),
            )
        )

        prev_water_depth = water_depth
        prev_stacking = stacking
        prev_eustatic = eustatic_m

    # Reverse to chronological order (youngest first = present day)
    steps.reverse()

    # Collect emergent patterns
    emergent = list(dict.fromkeys(s.stacking_pattern for s in steps))

    return AccommodationResult(
        steps=steps,
        total_subsidence_m=round(cumulative_subsidence_m, 1),
        total_eustatic_change_m=round(
            (steps[-1].eustatic_sea_level_m - steps[0].eustatic_sea_level_m) if steps else 0,
            1,
        ),
        total_sediment_m=round(cumulative_sediment, 1),
        num_flooding_surfaces=sum(1 for s in steps if s.is_flooding_surface),
        num_erosion_surfaces=sum(1 for s in steps if s.surface_type == SurfaceType.EROSION),
        num_sequence_boundaries=sum(1 for s in steps if s.is_sequence_boundary),
        num_maximum_flooding=sum(1 for s in steps if s.is_maximum_flooding),
        emergent_stacking=emergent,
        confidence=0.75,
        epistemic_label="DER",
        assumptions=[
            "Airy isostasy (no flexural rigidity — valid for basins < 200 km)",
            "Athy exponential porosity-depth law (no overpressure)",
            "1D simulation at a reference point (not 2D/3D)",
            "Sediment supply constant or linearly varying",
            "No autogenic processes (delta lobe switching, avulsion)",
        ],
        evidence_gaps=[
            "observed_subsidence_curve",
            "eustatic_calibration_data",
            "sediment_compaction_measurements",
            "paleobathymetry_markers",
        ],
        note=(
            f"Physics-first accommodation: {req.duration_ma} Ma, "
            f"{len(steps)} steps. "
            f"Sequences emerged from subsidence + eustasy + sediment, not from taxonomy rules."
        ),
    )


__all__ = [
    "SurfaceType",
    "StackingPattern",
    "EustaticPoint",
    "AccommodationRequest",
    "AccommodationStep",
    "AccommodationResult",
    "simulate_accommodation",
    "tectonic_subsidence_at_time",
    "sediment_load_isostasy",
    "decompact_thickness",
    "get_eustatic_level",
]
