#!/usr/bin/env python3
"""Regenerate the README status block between GEOX:GENERATED markers.

NOT part of the six CI-gated surfaces: this block embeds a LIVE organ probe
(:8081/drift, :8081/health) that CI cannot reproduce. The README's truth rule
already says live probes beat static counts — this script refreshes the
snapshot. Run it on the VPS (or anywhere the organ is reachable) whenever the
surface or runtime moves, then commit.

Usage: PYTHONPATH=src python3 scripts/generate_readme_status.py [--check]
"""

from __future__ import annotations

import json
import subprocess
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

START = "<!-- GEOX:GENERATED:STATUS:START -->"
END = "<!-- GEOX:GENERATED:STATUS:END -->"


def _probe(url: str, timeout: float = 3.0) -> dict | None:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return json.loads(r.read().decode())
    except Exception:
        return None


def build_block() -> str:
    from geox_mcp.registry import CANONICAL_PUBLIC_TOOLS, INTERNAL_TOOLS, tools_for_profile
    from geox_mcp.surface_manifest import surface_attestation

    drift = _probe("http://127.0.0.1:8081/drift") or {}
    health = _probe("http://127.0.0.1:8081/health") or {}

    try:
        main_sha = subprocess.check_output(
            ["git", "rev-parse", "--short", "main"], cwd=ROOT, text=True
        ).strip()
    except Exception:
        main_sha = "unknown"
    try:
        branch = subprocess.check_output(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=ROOT, text=True
        ).strip()
        head = subprocess.check_output(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, text=True
        ).strip()
    except Exception:
        branch, head = "unknown", "unknown"

    runtime_commit = str(health.get("git_version") or health.get("identity", {}).get("value") or "UNKNOWN")
    profile_counts = {}
    for p in ("default", "specialist", "research"):
        try:
            profile_counts[p] = len(tools_for_profile(p))
        except Exception:
            profile_counts[p] = "?"

    att = surface_attestation()

    lines = [
        START,
        f"<!-- GENERATED by scripts/generate_readme_status.py — {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%MZ')}. Probe beats this snapshot; regenerate rather than hand-edit. -->",
        "",
        f"- Canonical surface: **{len(CANONICAL_PUBLIC_TOOLS)}** tools (`registry.py::CANONICAL_PUBLIC_TOOLS` — gate-enforced SOT)",
        f"- Live organ (`:8081/drift`): canonical **{drift.get('canonical_count', 'UNKNOWN')}** · live **{drift.get('live_count', 'UNKNOWN')}** · drift **{drift.get('drift_count', 'UNKNOWN')}** · gap **{drift.get('gap_count', 'UNKNOWN')}** · ok **{str(drift.get('ok', 'UNKNOWN')).lower()}**",
        f"- Runtime commit: `{runtime_commit}` · source HEAD `{head}` (`{branch}`) · `main` at `{main_sha}` — a runtime on a feature branch is **source-vs-runtime lag by design until merged**; `main` itself is only truthful after deploy from `main`",
        f"- Discovery profiles: default **{profile_counts.get('default', '?')}** · specialist **{profile_counts.get('specialist', '?')}** · research **{profile_counts.get('research', '?')}** (pack policy, not the gate)",
        f"- Internal (hidden, executable in-process): **{len(INTERNAL_TOOLS)}** names — `registry.py::INTERNAL_TOOLS`, never on `tools/list`",
        f"- Surface attestation: `ok={att.get('ok')}`{(' · error=' + str(att.get('error'))) if att.get('error') else ''} — `public_count_target` is held at 31 by sovereign decision; see Open defects",
        f"- Generated surfaces in sync: **run `scripts/generate_all_surfaces.py --check`** (CI-gated; this block is not one of them)",
        END,
    ]
    return "\n".join(lines)


def main() -> int:
    check = "--check" in sys.argv
    path = ROOT / "README.md"
    text = path.read_text()
    if START not in text or END not in text:
        print("status markers missing from README.md", file=sys.stderr)
        return 1
    pre = text.split(START, 1)[0]
    post = text.split(END, 1)[1]
    new = pre + build_block() + post
    if new == text:
        print("README status block: in sync")
        return 0
    if check:
        print("README status block: STALE (run scripts/generate_readme_status.py)")
        return 1
    path.write_text(new)
    print("README status block: regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
