#!/usr/bin/env python3
"""publish_docroot.py — GEOX_APP_LAW compliant web publication.

GEOX_APP_LAW: publish to /var/www/html/geox, never hand-edit.
This script is the publish step: it syncs generator-owned surface artifacts
from the repo (all regenerated by generate_all_surfaces.py from registry.py
truth) and patches the count-bearing lines in the static landing files from
the same truth. Run after every surface regeneration.

Usage: python3 scripts/publish_docroot.py [--dry-run]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCROOT = Path("/var/www/html/geox")
DRY = "--dry-run" in sys.argv

SURFACE = json.loads((REPO / "src/geox_mcp/generated/CANONICAL_PUBLIC_SURFACE.json").read_text())
N = SURFACE["public_count"]
LIVE = set(SURFACE["public_tools"])
assert N == 27, f"registry truth says {N}; expected 27 — regenerate surfaces first"

SYNC = ["llms.txt", "tools.json", "CANONICAL_PUBLIC_SURFACE.json",
        "GEOX_MCP_APPS_SURFACE.json", "apps.json"]

PATCHES = {
    "index.html": [(rf"{n} public MCP tools", f"{N} public MCP tools") for n in (25, 31, 32, 42)],
    "profile.json": [(rf'"mcp_tools": {n}', f'"mcp_tools": {N}') for n in (25, 31, 32, 42)],
    "llms-full.txt": [(rf"{n} tools", f"{N} tools") for n in (25, 31, 32, 42)]
                     + [(rf"{n} governed MCP tools", f"{N} governed MCP tools") for n in (25, 31, 32)],
}

receipt = {"generated_from": f"registry truth ({N} tools)", "synced": [], "patched": {}, "skipped": []}

for name in SYNC:
    src, dst = REPO / name, DOCROOT / name
    if not src.exists():
        receipt["skipped"].append(f"{name} (missing in repo)")
        continue
    if not DRY:
        dst.write_text(src.read_text())
    receipt["synced"].append(name)

for name, subs in PATCHES.items():
    p = DOCROOT / name
    if not p.exists():
        receipt["skipped"].append(f"{name} (missing in docroot)")
        continue
    text = p.read_text()
    before = text
    hits = []
    for pat, rep in subs:
        m = re.search(pat, text)
        if m:
            hits.append(m.group(0))
            text = re.sub(pat, rep, text, count=1)
    if text != before and not DRY:
        p.write_text(text)
    receipt["patched"][name] = hits

print(json.dumps(receipt, indent=1))

# Postcondition: no stale counts left in docroot count-bearing lines
stale = []
for name in ("index.html", "profile.json", "llms.txt", "llms-full.txt", "tools.json"):
    p = DOCROOT / name
    if not p.exists():
        continue
    text = p.read_text()
    for bad in ("31 public MCP tools", "31 governed MCP tools", "42 tools",
                '"mcp_tools": 31', "42 governed"):
        if bad in text:
            stale.append(f"{name}: {bad}")
if stale:
    print("STALE REMNANTS:", stale)
    sys.exit(1)
print(f"POSTCONDITION OK: docroot count-bearing lines all state {N}")
