#!/usr/bin/env python3
"""publish_docroot.py — GEOX_APP_LAW compliant web publication.

GEOX_APP_LAW: publish to /var/www/html/geox, never hand-edit.
This script is the publish step: it syncs generator-owned surface artifacts
from the repo (all regenerated by generate_all_surfaces.py from registry.py
truth) and patches the count-bearing lines in the static landing files from
the same truth. Run after every surface regeneration.

Usage: python3 scripts/publish_docroot.py [--dry-run]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
DOCROOT = Path("/var/www/html/geox")
DRY = "--dry-run" in sys.argv

SURFACE = json.loads((REPO / "src/geox_mcp/generated/CANONICAL_PUBLIC_SURFACE.json").read_text())
N = SURFACE["public_count"]
LIVE = set(SURFACE["public_tools"])
assert N == 27, f"registry truth says {N}; expected 27 — regenerate surfaces first"

SYNC = ["llms.txt", "tools.json", "CANONICAL_PUBLIC_SURFACE.json",
        "GEOX_MCP_APPS_SURFACE.json", "apps.json"]

PATCHES = {
    "index.html": [(rf"{n} public MCP tools", f"{N} public MCP tools") for n in (25, 31, 32, 42)],
    "profile.json": [(rf'"mcp_tools": {n}', f'"mcp_tools": {N}') for n in (25, 31, 32, 42)],
    "llms-full.txt": [(rf"{n} tools", f"{N} tools") for n in (25, 31, 32, 42)]
                     + [(rf"{n} governed MCP tools", f"{N} governed MCP tools") for n in (25, 31, 32)],
}

receipt = {"generated_from": f"registry truth ({N} tools)", "synced": [], "patched": {}, "skipped": []}

# ── LIVE APPS publish (2026-10-03: webroot /apps/ was EMPTY — MCP Apps cards landed on SPA theater) ──
import shutil

APPS_SRC = Path("/opt/geox/apps")
APPS_DST = DOCROOT / "apps"
if APPS_SRC.exists():
    APPS_DST.mkdir(parents=True, exist_ok=True)
    published = []
    for d in sorted(APPS_SRC.iterdir()):
        if d.is_dir() and (d / "index.html").exists():
            dst = APPS_DST / d.name
            if not DRY:
                if dst.exists():
                    shutil.rmtree(dst)
                shutil.copytree(d, dst)
            published.append(d.name)
    receipt["synced"].append(f"apps/ ({len(published)}: {', '.join(published)})")

# ── Landing truth patch (minified bundle carries pre-consolidation counts) ──
# Verified live truth only; unverified numbers are left untouched.
LANDING_PATCHES = [
    ("42 tools, 18 GUI apps", "27 tools, GUI apps"),
    ("42 tools. Live surface.", "27 tools. Live surface."),
    ('"tools": 42', '"tools": 27'),
    ("42 tools over SSE at :8081", "27 tools over streamable-http at :8081"),
    ('"transport": "sse"', '"transport": "streamable-http"'),
    ("42 tools · 18 apps", f"27 tools · {len(list(APPS_DST.glob('*/index.html')))} apps"),
    # dead pre-consolidation sample invocations -> live canonical equivalents
    ("geox.egs_data_qc_bundle()", "geox.well_qc()"),
    ("geox.egs_query_uncertainty()", "geox.prospect()"),
    ("geox.egs_rock_physics()", "geox.geomechanics()"),
    ("geox.egs_scenario_audit()", "geox.claim()"),
    ("geox.witness_well()", "geox.well()"),
    ("arifos.bridge_contract()", "arifos.arif_route()"),
]

def patch_landing() -> None:
    targets = [DOCROOT / "index.html"] + list((DOCROOT / "assets").glob("index-*.js"))
    # static well-known manifest, if present on disk
    wk = DOCROOT / ".well-known" / "mcp.json"
    if wk.exists():
        targets.append(wk)
    for f in targets:
        if not f.exists():
            continue
        text = before = f.read_text()
        hits = 0
        for old, new in LANDING_PATCHES:
            hits += text.count(old)
            text = text.replace(old, new)
        if text != before:
            if not DRY:
                f.write_text(text)
            receipt["patched"][str(f.relative_to(DOCROOT))] = f"{hits} truth fixes"

patch_landing()

# ── Earth Witness CTA banner (2026-10-03, sovereign: "mana butang aku nak click?") ──
# Static, marker-delimited, idempotent — survives SPA bundle rebuilds only until
# the marker is stripped; the proper fix is restoring the landing SPA source.
BANNER_OPEN = "<!-- EARTH-WITNESS-CTA:START (owned by scripts/publish_docroot.py) -->"
BANNER = BANNER_OPEN + """
<div id="ew-cta-bar" style="position:sticky;top:0;z-index:9999;display:flex;align-items:center;justify-content:center;gap:16px;padding:10px 16px;background:#0b1220;color:#e8eefc;font-family:system-ui,sans-serif;font-size:15px;border-bottom:1px solid #233252">
  <a href="/observe/" style="display:inline-block;padding:9px 20px;border-radius:8px;background:#2f6df6;color:#fff;font-weight:700;text-decoration:none">🪨 Earth Witness — Tanya Bumi</a>
  <span style="opacity:.85">Chat langsung dengan organ geoscience &middot; <a href="/mcp-apps/" style="color:#8fb3ff">semua apps</a> &middot; <a href="/gui/" style="color:#8fb3ff">WellDesk GUI</a></span>
</div>
<!-- EARTH-WITNESS-CTA:END -->
"""

def inject_banner(text: str) -> tuple[str, bool]:
    if BANNER_OPEN in text:
        return text, False
    for anchor in ("<body>", "<body ", "<body>"):
        idx = text.find(anchor)
        if idx != -1:
            return text[: idx + len(anchor)] + BANNER + text[idx + len(anchor) :], True
    return text, False

for name in ("index.html",):
    p = DOCROOT / name
    if not p.exists():
        receipt["skipped"].append(f"{name} (missing in docroot)")
        continue
    new_text, changed = inject_banner(p.read_text())
    if changed and not DRY:
        p.write_text(new_text)
    receipt["patched"][f"{name}#ew-cta"] = "injected" if changed else "already present"

for name in SYNC:
    src, dst = REPO / name, DOCROOT / name
    if not src.exists():
        receipt["skipped"].append(f"{name} (missing in repo)")
        continue
    if not DRY:
        dst.write_text(src.read_text())
    receipt["synced"].append(name)

for name, subs in PATCHES.items():
    p = DOCROOT / name
    if not p.exists():
        receipt["skipped"].append(f"{name} (missing in docroot)")
        continue
    text = p.read_text()
    before = text
    hits = []
    for pat, rep in subs:
        m = re.search(pat, text)
        if m:
            hits.append(m.group(0))
            text = re.sub(pat, rep, text, count=1)
    if text != before and not DRY:
        p.write_text(text)
    receipt["patched"][name] = hits

print(json.dumps(receipt, indent=1))

# Postcondition: no stale counts left in docroot count-bearing lines
stale = []
for name in ("index.html", "profile.json", "llms.txt", "llms-full.txt", "tools.json"):
    p = DOCROOT / name
    if not p.exists():
        continue
    text = p.read_text()
    for bad in ("31 public MCP tools", "31 governed MCP tools", "42 tools",
                '"mcp_tools": 31', "42 governed"):
        if bad in text:
            stale.append(f"{name}: {bad}")
if stale:
    print("STALE REMNANTS:", stale)
    sys.exit(1)
print(f"POSTCONDITION OK: docroot count-bearing lines all state {N}")
