# ─── _helpers.py ─── backward-compatibility shim ───────────────────────────
# AUTO-GENERATED by Stage 1 extraction: kernel layer split
# Original 1,363-line _helpers.py split into 5 kernel modules:
#   kernel/_registry.py      ← artifact registry + globals (lines 1–192)
#   kernel/_evidence.py     ← F6 Maruah + F7 ensemble (lines 193–311)
#   kernel/_ingest.py       ← ingest + canonical curves (lines 312–451)
#   kernel/_petrophysics.py ← petrophysics (lines 453–1042)
#   kernel/_candidates.py   ← async subsurface candidates (lines 1043–1363)
#
# This shim re-exports everything so existing imports continue to work.
# NO BUSINESS LOGIC HERE — all logic lives in kernel/

__all__ = []  # populated below

# ─── Import kernel layer ───────────────────────────────────────────────────
from .kernel import _registry
from .kernel import _evidence
from .kernel import _ingest
from .kernel import _petrophysics
from .kernel import _candidates

# ─── Global state (lives in kernel/_registry.py) ─────────────────────────
# These are the in-memory stores — imported from kernel for backward compat
_artifact_registry = _registry._artifact_registry
_well_curves_registry = _registry._well_curves_registry
_artifact_store = _registry._artifact_store
_ARTIFACT_REGISTRY_PATH = _registry._ARTIFACT_REGISTRY_PATH
MAX_UPLOAD_BYTES = _registry.MAX_UPLOAD_BYTES
Path = _registry.Path

# ─── Constants ───────────────────────────────────────────────────────────
CLAIM_STATES = _ingest.CLAIM_STATES
CANONICAL_ALIASES = _ingest.CANONICAL_ALIASES
_CURVE_RANGES = _ingest._CURVE_RANGES

# ─── Registry functions (kernel/_registry.py) ────────────────────────────
_normalize_artifact_ref = _registry._normalize_artifact_ref
__all__.append("_normalize_artifact_ref")
_artifact_aliases = _registry._artifact_aliases
__all__.append("_artifact_aliases")
_safe_artifact_filename = _registry._safe_artifact_filename
__all__.append("_safe_artifact_filename")
_load_artifact_registry_from_disk = _registry._load_artifact_registry_from_disk
__all__.append("_load_artifact_registry_from_disk")
_persist_artifact_registry = _registry._persist_artifact_registry
__all__.append("_persist_artifact_registry")
_register_artifact = _registry._register_artifact
__all__.append("_register_artifact")
_get_artifact = _registry._get_artifact
__all__.append("_get_artifact")
_artifact_exists = _registry._artifact_exists
__all__.append("_artifact_exists")
_record_latest_qc = _registry._record_latest_qc
__all__.append("_record_latest_qc")
_latest_qc_failed_refs = _registry._latest_qc_failed_refs
__all__.append("_latest_qc_failed_refs")

# ─── Evidence functions (kernel/_evidence.py) ─────────────────────────────
_bbox_intersects = _evidence._bbox_intersects
__all__.append("_bbox_intersects")
_inject_ensemble_residual_evidence = _evidence._inject_ensemble_residual_evidence
__all__.append("_inject_ensemble_residual_evidence")
_check_maruah_territory = _evidence._check_maruah_territory
__all__.append("_check_maruah_territory")

# ─── Ingest + curve functions (kernel/_ingest.py) ───────────────────────
_safe_upload_path = _ingest._safe_upload_path
__all__.append("_safe_upload_path")
_decode_upload_content = _ingest._decode_upload_content
__all__.append("_decode_upload_content")
_map_canonical_curves = _ingest._map_canonical_curves
__all__.append("_map_canonical_curves")
_detect_depth_unit = _ingest._detect_depth_unit
__all__.append("_detect_depth_unit")
_parse_csv_or_json = _ingest._parse_csv_or_json
__all__.append("_parse_csv_or_json")

# ─── Petrophysics functions (kernel/_petrophysics.py) ────────────────────
_compute_vsh_from_store = _petrophysics._compute_vsh_from_store
__all__.append("_compute_vsh_from_store")
_compute_porosity_from_store = _petrophysics._compute_porosity_from_store
__all__.append("_compute_porosity_from_store")
_compute_saturation_from_store = _petrophysics._compute_saturation_from_store
__all__.append("_compute_saturation_from_store")
_compute_netpay_from_store = _petrophysics._compute_netpay_from_store
__all__.append("_compute_netpay_from_store")
_classify_gr_motif = _petrophysics._classify_gr_motif
__all__.append("_classify_gr_motif")
_classify_lithology_from_store = _petrophysics._classify_lithology_from_store
__all__.append("_classify_lithology_from_store")
_safe_reduction = _petrophysics._safe_reduction
__all__.append("_safe_reduction")
_get_well_data_with_depth = _petrophysics._get_well_data_with_depth
__all__.append("_get_well_data_with_depth")

# ─── Async candidates (kernel/_candidates.py) ────────────────────────────
_compute_subsurface_candidates = _candidates._compute_subsurface_candidates
__all__.append("_compute_subsurface_candidates")